[package]
name = "ktk"
version = "0.14.7"
authors = ["https://framagit.org/gauthier/ktk"]
edition = "2021"
description = "Kitty Tab for Kubeconfig"
license = "MIT"
readme = "README.adoc"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.1", features = ["cargo", "string"] }
config = "0.13.3"
dirs = "5.0.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
time = "0.3.21"
skim = "0.10.4"
wait-timeout = "0.2.0"
simplelog = { version = "^0.11.0", features = ["paris"] }
log = "0.4.17"
color-print = "0.3.4"
