= ktk - Kitty Tab pour Kubeconfig

`ktk` est un outil en ligne de commande permettant de gérer l'utilisation de multiple fichiers kubeconfig simultanément dans des onglets kitty.

Il est possible de personnaliser le nom et la couleur des onglets pour chaque cluster, de rechercher rapidement dans des milliers de namespaces, grace à un cache.

Enfin, au moment de l'ouverture de l'onglet de se placer directement dans un répertoire de travail spécifique au cluster et au namespace.

`ktk` peut gérer facilement des dizaines de clusters avec des milliers de namespaces.

== Pré requis

`ktk` a besoin pour fonctionner des outils `kubectl` et https://sw.kovidgoyal.net/kitty/[kitty].
Et bien sûr d'un ou plusieurs clusters Kubernetes à gérer.

== Installation

Copier le fichier de configuration `config.sample.yaml` dans le fichier `~/.config/ktk.yaml`

Personnaliser le fichier pour déclarer vos serveurs Kubernetes.

Ajouter l'option `allow_remote_control yes` dans le fichier de configuration kitty.conf

Et lancer kitty avec l'option `-1` pour n'avoir qu'une seule instance kitty.

=== Fichier de configuration `~/.config/ktk.yaml`

==== Section global

Dans cette section, nous déclarons les paramétrages globale de l'application.

[source,yaml]
----
global:
  kubetmp: "/run/user/1000/.kubeconfig"
  separator: "::"
  completion:
    file: "/home/user/.kube/tkcompleted"
    maxage: 43200
  tabprefix: "☸>>"
----

* kubetmp: dossier temporaire où sont copiés les fichiers kubeconfig temporaire.
* separator: séparation entre le nom du namespace et du cluster dans le fichier de cache et dans la recherche.
* completion->file: Nom du fichier de cache pour la recherche de namespace.
* completion->maxage: Durée de validité du cache en secondes.
* tabprefix: préfixe dans le nom du tab, ex: "☸>>kube-system::prod".

==== Paramétrages communs aux clusters

Pour éviter de ressaisir des informations identiques pour chaque cluster, il est possible d'utiliser le système d'ancre du fichier yaml.

[source,yaml]
----
.workdir: &workdir
  path: "/home/user/jenkins/deploy"
  subdir: "."
  prefixns: ""

.kubeconfig: &kubeconfig
  path: "/home/user/.kube/konfigs"
  file: "default"
----

* workdir: dossier de travail lorsque l'on travaille dans un namespace.
* path: chemin principal
* subdir: chemin spécifique au namespace
* prefix: préfixe a retirer du nom du namespace. Exemple: `prod-` pour un namespace du style `prod-mon-application`. Le chemin sera donc `/home/user/jenkins/deploy/mon-application` et non `/home/user/jenkins/deploy/prod-mon-application`.

* kubeconfig->path: dossier contenant le fichier kubeconfig du cluster
* kubeconfig->file: Nom du fichier kubeconfig.

==== Section clusters

On retrouve ici les paramétrages spécifiques à chaque cluster.

[source,yaml]
----
clusters:
  - name: prod
    kitty:
      tabactivebg: "#db4b4b"
      tabinactivefg: "#8e3533"
    workdir:
      <<: *workdir
      subdir: "prod_conf"
    kubeconfig:
      <<: *kubeconfig
      file: "prod"
----

* kitty->tabactivebg: couleur de fond de l'onglet actif pour le cluster
* kitty->tabinactivefg: couleur du texte de l'onglet inactif pour le cluster

=== Modification de `bashrc` ou `zshrc`

Il n'est pas possible de changer de répertoire depuis un executable, le programme va donc afficher les commandes `export` et `cd` qui seront évaluées par `eval`.

[source,bash]
----
if kubedir=$(~/.local/bin/ktk --evaldir); then
  eval "$(echo $kubedir)"
  source <(kubectl completion zsh)
  source <(stern --completion zsh)
  # ...
else
  export KUBECONFIG=/dev/null
fi
----

Ici j'en profite pour ne charger les outils de completion automatique que si cela est nécessaire.

== Utilisation

[source,bash]
----
# ktk -h

Usage: ktk [OPTIONS] [namespace]

Arguments:
  [namespace]  Namespace to operate on

Options:
  -c, --config <FILE>  Sets a custom config file [default: /home/user/.config/ktk.yaml]
  -f, --force...       Force reconstruct cache of namespace
  -t, --tab...         Change namespace without change tab
  -n, --noscan...      Don't reconstruct cache of namespace
  -e, --evaldir...     Show in stdout workdir of current cluster
  -h, --help           Print help
  -V, --version        Print version
----

Pour ouvrir un nouvel onglet avec le contexte du cluster prod pour le namespace default :

[source,bash]
----
# ktk default::prod
----

Un nouvel onglet qui aura pour nom `☸>>default::prod` est ouvert avec le bon context `kubeconfig`.
Si l'on relance la commande, le focus sera fait sur l'onglet qui porte déjà le même nom.

La première fois que la commande est lancée, `ktk` va analyser l'ensemble des clusters pour récupérer la liste des namespaces et stocker ces informations dans le cache.

Pour forcer l'expiration du cache (qui par défaut dure `maxage` secondes), notamment lorsque je viens de créer un nouveau namespace, il suffit de choisir l'option `-f` comme ceci:

[source,bash]
----
# ktk -f new-namespace::prod
----

Si le nom du namespace n'est pas complet, `ktk` ouvre une fenêtre de dialogue pour demander de choisir dans la liste des namespaces possible, celui que l'on désire atteindre.

[source,bash]
----
  test5::prod
  temp-stage-ns::dev
> test1-namespace::sandbox
 3/32
> test
----
