= ktk - Kitty Tab for Kubeconfig

`ktk` is a command line tool to manage multiple kubeconfig files simultaneously in different kitty tabs.

It is possible to customize the name and the color of the tabs for each cluster, to search quickly in thousands of namespaces, with a cache file.

When `ktk` open a new tab, you go directly to a working directory specific to the cluster and the namespace.

`ktk` can easily manage dozens of clusters with thousands of namespaces.

== Prerequisites

`ktk` needs the `kubectl` and https://sw.kovidgoyal.net/kitty/[kitty] tools to work. And of course one or more Kubernetes clusters to manage.

== Install

Copy the `config.sample.yaml` configuration file to the `~/.config/ktk.yaml` file

Customize the file to declare your Kubernetes servers.

Add the option `allow_remote_control yes` in the configuration file `kitty.conf`

And launch `kitty` with the `-1` option to have only one kitty instance.

=== Configuration file `~/.config/ktk.yaml`

==== Global section

In this section we declare the global settings of the application.

[source,yaml]
----
global:
  kubetmp: "/run/user/1000/.kubeconfig"
  separator: "::"
  completion:
    file: "/home/user/.kube/tkcompleted"
    maxage: 43200
  tabprefix: "☸>>"
----

* kubetmp: folder where temporary kubeconfig files are copied.
* separator: separation between namespace and cluster name in the cache file and in the search.
* completion→file: name of the cache file for the namespace search.
* completion→maxage: Duration of cache validity in seconds.
* tabprefix: prefix in the tab name, e.g. `☸>>kube-system::prod`.

==== Common settings for clusters

To avoid re-entering identical information for each cluster, it is possible to use the anchor system of the yaml file.

[source,yaml]
----
.workdir: &workdir
  path: "/home/user/jenkins/deploy"
  subdir: "."
  prefixns: ""

.kubeconfig: &kubeconfig
  path: "/home/user/.kube/konfigs"
  file: "default"
----

* workdir: working folder when working in a namespace.
* path: main path
* subdir: namespace specific path
* prefix: prefix to remove from the namespace name. Example: `prod-` for a namespace like prod-mon-application. So the path will be `/home/user/jenkins/deploy/my-application` and not `/home/user/jenkins/deploy/prod-mon-application`.

* kubeconfig→path: folder containing the kubeconfig file of the cluster
* kubeconfig→file: name of the kubeconfig file.

==== Clusters section

Here are the specific settings for each cluster.

[source,yaml]
----
clusters:
  - name: prod
    kitty:
      tabactivebg: "#db4b4b"
      tabinactivefg: "#8e3533"
    workdir:
      <<: *workdir
      subdir: "prod_conf"
    kubeconfig:
      <<: *kubeconfig
      file: "prod"
----

* kitty→tabactivebg: background color of the active tab for the cluster
* kitty→tabinactivefg: text color of the inactive tab for the cluster

=== Changing bashrc or zshrc

It is not possible to change the directory from an executable, so the program will display the export and cd commands which will be evaluated by eval.

[source,bash]
----
if kubedir=$(~/.local/bin/ktk --evaldir); then
  eval "$(echo $kubedir)"
  source <(kubectl completion zsh)
  source <(stern --completion zsh)
  # ...
else
  export KUBECONFIG=/dev/null
fi
----

Here I take the opportunity to load the automatic completion tools only if necessary.

== Usage

[source,bash]
----
# ktk -h

Usage: ktk [OPTIONS] [namespace]

Arguments:
  [namespace]  Namespace to operate on

Options:
  -c, --config <FILE>  Sets a custom config file [default: /home/user/.config/ktk.yaml]
  -f, --force...       Force reconstruct cache of namespace
  -t, --tab...         Change namespace without change tab
  -n, --noscan...      Don't reconstruct cache of namespace
  -e, --evaldir...     Show in stdout workdir of current cluster
  -h, --help           Print help
  -V, --version        Print version
----

To open a new tab with the prod cluster context for the default namespace :

[source,bash]
----
# ktk default::prod
----

A new tab with the name `☸>>default::prod` is opened with the correct kubeconfig context. If the command is run again, the focus will be on the tab that already has the same name.

The first time the command is run, `ktk` will scan all the clusters to get the list of namespaces and store this information in the cache.

To force the expiration of the cache (which by default lasts maxage seconds), especially when I have just created a new namespace, I just have to choose the `-f` option like this:

[source,bash]
----
# ktk -f new-namespace::prod
----

If the name of the namespace is not complete, `ktk` opens a dialog to ask to choose in the list of possible namespaces, the one you want to reach.

[source,bash]
----
  test5::prod
  temp-stage-ns::dev
> test1-namespace::sandbox
 3/32
> test
----
