---
global:
  kubetmp: "/run/user/1000/.kubeconfig"
  separator: "@"
  completion:
    file: "~/.kube/tkcompleted"
    maxage: 86400
  tabprefix: "☸"


.workdir: &workdir
  path: "~/deploy"
  subdir: "."
  prefixns: ""

.kubeconfig: &kubeconfig
  path: "~/.kube/konfigs"
  file: "default"
  get-timeout-sec: 3
  connect-timeout-msec: 800

clusters:
  - name: prod
    kitty:
      tabactivebg: "#db4b4b"
      tabinactivefg: "#8e3533"
    workdir:
      <<: *workdir
      subdir: "deploy_env_prod"
    kubeconfig:
      <<: *kubeconfig
      file: "prod"
      timeout: 5

  - name: dev
    kitty:
      tabactivebg: "#7dcfff"
      tabinactivefg: "#5485a2"
    workdir:
      <<: *workdir
      subdir: "deploy_env_dev"
    kubeconfig:
      <<: *kubeconfig
      file: "dev"

  - name: test
    disabled: true
    kitty:
      tabactivebg: "#ff9e64"
      tabinactivefg: "#a36743"
    workdir:
      <<: *workdir
      subdir: deploy_env_test
      prefixns: "test-"
    kubeconfig:
      <<: *kubeconfig
      file: test
