---
global:
  kubetmp: "/run/user/1000/.kubeconfig"
  separator: "@"
  completion:
    file: "~/.kube/tkcompleted"
    maxage: 86400
  tabprefix: "☸"
  gradient:
    name: turbo
    reverse: true
  oh-my-posh:
    file: "conf/theme.json"


.workdir: &workdir
  path: "~/deploy"
  subdir: "."
  prefixns: ""

.kubeconfig: &kubeconfig
  path: "~/.kube/konfigs"
  file: "default"
  get-timeout-sec: 3
  connect-timeout-msec: 800

clusters:
  - name: other
    disabled: true
    workdir:
      <<: *workdir
      subdir: deploy_env_other
      prefixns: ""
    kubeconfig:
      <<: *kubeconfig
      file: other

  - name: prod
    workdir:
      <<: *workdir
      subdir: "deploy_env_prod"
    kubeconfig:
      <<: *kubeconfig
      file: "prod"
      timeout: 5

  - name: dev
    workdir:
      <<: *workdir
      subdir: "deploy_env_dev"
    kubeconfig:
      <<: *kubeconfig
      file: "dev"

  - name: test
    workdir:
      <<: *workdir
      subdir: deploy_env_test
      prefixns: "test-"
    kubeconfig:
      <<: *kubeconfig
      file: test
